- .github/workflows/solana-integration.yml
Adds basic CI for the `solana/integration` branch; includes Clippy checks as well as `cargo` and `anchor` tests.
Tests should pass.
> solana: add basic CI for solana integration branch

- solana/programs/matching-engine/src/processor/auction/offer/improve.rs
- solana/programs/matching-engine/src/processor/auction/prepare_settlement/cctp.rs
Fixes some comments.
- Fixes an incorrect comment describing the offer improvement token transfer flow
- Fixes outdated comment in prepare order response flow
N/A
> solana: fix several comments

- solana/ts/tests/01__matchingEngine.ts
- solana/ts/tests/02__tokenRouter.ts
- solana/ts/tests/04__interaction.ts
Adds several negative tests for the matching engine and token router.
Added new tests; tests should pass.
> solana: add negative tests for MatchingEngine and TokenRouter

- solana/ts/src/matchingEngine/index.ts
- solana/ts/tests/01__matchingEngine.ts
- solana/ts/tests/04__interaction.ts
Fixes active auction instructions (and one "none auction" instruction) to fetch `preparedOrderResponse` if it's undefined when passed as a parameter.
Adjusted corresponding tests to pass in an undefined `preparedOrderResponse`.
> solana: fetch `preparedOrderResponse` if undefined

- solana/programs/matching-engine/src/processor/admin/propose/mod.rs
- solana/programs/matching-engine/src/processor/admin/update/auction_parameters.rs
- solana/target/idl/matching_engine.json
- solana/target/types/matching_engine.ts
- solana/ts/src/matchingEngine/index.ts
- solana/ts/tests/01__matchingEngine.ts
This PR makes a few adjustments to the proposals workflow.
Tests should pass.
> solana: adjustments to proposals

- solana/programs/matching-engine/src/processor/admin/migrate.rs
- solana/programs/upgrade-manager/src/processor/matching_engine_upgrade/commit.rs
- solana/programs/upgrade-manager/src/processor/matching_engine_upgrade/execute.rs
- solana/target/idl/matching_engine.json
- solana/target/idl/upgrade_manager.json
- solana/target/types/matching_engine.ts
- solana/target/types/upgrade_manager.ts
- solana/ts/src/upgradeManager/index.ts
- solana/ts/tests/12__testnetFork.ts
Fixes #43 due to incorrect Custodian serialization.
> solana: modify migrate from legacy custodian

- solana/modules/common/src/constants/mod.rs
- solana/programs/matching-engine/src/processor/auction/offer/place_initial.rs
- solana/ts/tests/01__matchingEngine.ts
- solana/ts/tests/04__interaction.ts
- solana/ts/tests/helpers/mock.ts
- solana/ts/tests/helpers/utils.ts
This PR adds a check in `place_initial_offer` that will revert if the Vaa timestamp is expired (2 hours old). This PR is necessary for #28.
> solana: add vaa timestamp check

- solana/programs/matching-engine/src/composite/mod.rs
- solana/programs/matching-engine/src/error.rs
- solana/programs/matching-engine/src/processor/admin/update/owner_assistant.rs
- solana/programs/token-router/src/error.rs
- solana/programs/token-router/src/processor/admin/initialize.rs
- solana/programs/token-router/src/processor/admin/update/owner_assistant.rs
- solana/programs/upgrade-manager/src/error.rs
- solana/target/idl/matching_engine.json
- solana/target/idl/token_router.json
- solana/target/idl/upgrade_manager.json
- solana/target/types/matching_engine.ts
- solana/target/types/token_router.ts
- solana/target/types/upgrade_manager.ts
- solana/ts/tests/01__matchingEngine.ts
- solana/ts/tests/02__tokenRouter.ts
> solana: assign values to all errors

- solana/Makefile
- solana/programs/matching-engine/src/error.rs
- solana/programs/matching-engine/src/processor/auction/offer/place_initial.rs
- solana/programs/matching-engine/src/state/auction_config.rs
- solana/programs/matching-engine/src/utils/auction.rs
- solana/target/idl/matching_engine.json
- solana/target/types/matching_engine.ts
- solana/ts/src/matchingEngine/index.ts
- solana/ts/src/matchingEngine/state/AuctionConfig.ts
- solana/ts/tests/01__matchingEngine.ts
> solana: add security deposit params

- solana/programs/matching-engine/src/composite/mod.rs
- solana/programs/matching-engine/src/processor/auction/execute_fast_order/cctp.rs
- solana/programs/matching-engine/src/processor/auction/execute_fast_order/local.rs
- solana/programs/matching-engine/src/processor/auction/execute_fast_order/mod.rs
- solana/programs/matching-engine/src/processor/auction/settle/none/cctp.rs
- solana/programs/matching-engine/src/processor/auction/settle/none/local.rs
- solana/programs/matching-engine/src/processor/auction/settle/none/mod.rs
- solana/target/idl/matching_engine.json
- solana/target/types/matching_engine.ts
- solana/ts/src/matchingEngine/index.ts
- solana/ts/tests/01__matchingEngine.ts
This also fixes the settle auction none instructions by closing the prepared custody token accounts.
> solana: remove cctp mint recipient; use set authority

- solana/programs/matching-engine/src/processor/admin/propose/mod.rs
Add a separate delay for Solana devnet (roughly 10 seconds) to change auction configs faster based on solver feedback.
> solana: testnet proposal delay

- solana/programs/matching-engine/src/events/enacted.rs
- solana/programs/matching-engine/src/events/mod.rs
- solana/programs/matching-engine/src/events/proposed.rs
- solana/programs/matching-engine/src/processor/admin/propose/auction_parameters.rs
- solana/programs/matching-engine/src/processor/admin/update/auction_parameters.rs
- solana/programs/matching-engine/src/state/proposal.rs
- solana/target/idl/matching_engine.json
- solana/target/types/matching_engine.ts
- solana/ts/src/matchingEngine/index.ts
Closes #72.
Depends on #73 for CI to pass.
> solana: add proposal events

- solana/Makefile
- solana/package-lock.json
- solana/package.json
- solana/ts/scripts/dedupeVaaExample.ts
- solana/ts/src/wormhole/spy.ts
Simple de-duping mechanism when listening to the Wormhole gossip network. All this uses is a map, which gets cleaned out based on some simple config parameters (interval for timeout, how many to remove at a time, time criteria for when to remove VAA hashes).
Also add to the Makefile a command to run the spy for testnet or mainnet.
> solana: add example VAA deduper

- solana/programs/matching-engine/src/error.rs
- solana/programs/matching-engine/src/processor/auction/settle/complete.rs
- solana/target/idl/matching_engine.json
- solana/target/types/matching_engine.ts
- solana/ts/tests/01__matchingEngine.ts
Require that the executor is the one who prepared the order response and custody token accounts.
Fixing the test made using the test method a bit uglier. We should clean this up in another PR.
> solana: require executor == prepared by for penalty

- solana/programs/matching-engine/src/events/order_executed.rs
- solana/programs/matching-engine/src/processor/auction/execute_fast_order/mod.rs
- solana/target/idl/matching_engine.json
- solana/target/types/matching_engine.ts
Adding source chain and penalized boolean.
Penalized boolean can be useful for those folks looking to collect the base fee in settling auctions where the winning participant was penalized for executing the order after the grace period.
> solana: fix order executed event

- solana/programs/matching-engine/src/error.rs
- solana/programs/matching-engine/src/processor/auction/execute_fast_order/mod.rs
- solana/programs/matching-engine/src/processor/auction/offer/improve.rs
- solana/target/idl/matching_engine.json
- solana/target/types/matching_engine.ts
- solana/ts/tests/01__matchingEngine.ts
In case token accounts are closed during the auction process, handle these cases by sending funds to the executor token when orders are executed.
> solana: handle non-existent token accounts

- solana/ts/src/matchingEngine/index.ts
This is just a simple fix in the TypeScript client that ensures that rent is paid by the actual transaction fee payer and not by the USDC account when placing an initial bid.
> solana: enable specifying rent payer in initial bid

- solana/.gitignore
- solana/programs/matching-engine/src/composite/mod.rs
- solana/programs/matching-engine/src/processor/auction/execute_fast_order/cctp.rs
- solana/programs/matching-engine/src/processor/auction/execute_fast_order/local.rs
- solana/programs/matching-engine/src/processor/auction/execute_fast_order/mod.rs
- solana/programs/matching-engine/src/processor/auction/settle/none/cctp.rs
- solana/programs/matching-engine/src/processor/auction/settle/none/local.rs
- solana/programs/token-router/src/processor/market_order/place_cctp.rs
- solana/target/idl/matching_engine.json
- solana/target/types/matching_engine.ts
- solana/ts/src/matchingEngine/index.ts
- solana/ts/tests/01__matchingEngine.ts
* Execute order should send auction custody token account lamports to the owner of the initial offer token if it exists
* Settle auction none should send prepared custody token lamports to prepared_by encoded in `PreparedOrderResponse`
* Place order CCTP should send prepared order token account lamports to prepared_by encoded in `PreparedOrder`
Closes #104.
> solana: fix lamport beneficiaries

- solana/programs/token-router/src/error.rs
- solana/programs/token-router/src/processor/market_order/prepare.rs
- solana/target/idl/token_router.json
- solana/target/types/token_router.ts
- solana/ts/src/tokenRouter/index.ts
- solana/ts/tests/02__tokenRouter.ts
If an integrator were to compose with prepare market order instruction, it may be difficult (not impossible) to determine the transfer authority seeds.
This allows for an integrator to choose passing in a `sender`, who has authority to transfer assets from the sender token account OR a `program_transfer_authority`, which is the transfer authority that already existed. **Both cannot be specified.**
> solana: add sender option

- solana/programs/matching-engine/src/processor/auction/settle/complete.rs
Same issue found in settling completed auctions as the one resolved in PR #125.
> solana: use custody token amount for repayment

- solana/README.md
For issue https://github.com/wormhole-foundation/example-liquidity-layer/issues/132
- Add wormhole-spy dependency explanation and how to run using Docker and make
- Mention adding `knownAtaOwners` to config for all token account owners for `settle_auction_complete` to work
- Mention adding `SOLANA_PRIVATE_KEYS` to `.env` file in base64 format
> solana: add more auction participant how-to to README

- solana/Makefile
- solana/README.md
- solana/docker-compose.yml
This PR uses [Beacon](https://github.com/pyth-network/beacon) by Pyth Network as `VaaSpy` instead of Wormhole Spy for improved spy availability and latency.
- `docker-compose.yml` to host both nats-server and Beacon
- add instruction to use Beacon
> solana: use docker compose to host nats and beacon for solvers

- solana/ts/src/matchingEngine/state/index.ts
`FastFillInfo` does not exist in `ReservedFastFillSequence`
> Remove export

- package-lock.json
- solana/package.json
Right now, it is not possible to use `@wormhole-foundation/example-liquidity-layer-solana` package outside this project:
```
unhandledRejection Error: Assertion failed
at assert (/Users/livthomas/Projects/rockawayx-labs/wormhole-solver/lib/example-liquidity-layer/node_modules/bn.js/lib/bn.js:6:21)
at BN._initArray (/Users/livthomas/Projects/rockawayx-labs/wormhole-solver/lib/example-liquidity-layer/node_modules/bn.js/lib/bn.js:145:5)
at BN.init [as _init] (/Users/livthomas/Projects/rockawayx-labs/wormhole-solver/lib/example-liquidity-layer/node_modules/bn.js/lib/bn.js:86:19)
at new BN (/Users/livthomas/Projects/rockawayx-labs/wormhole-solver/lib/example-liquidity-layer/node_modules/bn.js/lib/bn.js:39:12)
at constructor (/Users/livthomas/Projects/rockawayx-labs/wormhole-solver/lib/example-l …
```
> solana: add explicit bn.js dependency

- solana/ts/src/wormhole/index.ts
Before this change, it was not easy to get the original VAA hash when you fetched `VaaAccount` posted on chain.
> solana/ts: make original hash available in VaaAccount

- solver/Makefile
guardian: update xlabs testnet guardians
We are deprecating `nodes.stable.io` domains and created a new domains for guardian testnet instances.
> guardian: update xlabs testnet guardians

- solana/ts/src/matchingEngine/index.ts
This PR fixes incorrect type. Example `LocalFastOrderFilled`  order looks like this:
```
{
"process": "sync",
"data": {
"seeds": {
"sourceChain": 10003,
"orderSender": [...],
"sequence": "1281",
"bump": 255
},
"info": {
"preparedBy": "gyVfT39y3tWQnfXwxY6Hj7ZeLFN2K8Z6heWEJ4zxYRB",
"amount": "7a1200",
"redeemer": "D1LLYchgdMZ8M8j8XdvUzCYCjZXhTMXSAg6WS1SAi7oN",
"timestamp": "6672d177"
},
"auction": "DJcvFfdymRXFyCm42JNsVmVPDw5fX666iBaNCeC2hqg2"
}
} 
```
> solana: fix `LocalFastOrderFilled` type

- solana/ts/scripts/getTestnetInfo.ts
- solana/ts/scripts/setUpMatchingEngineLut.ts
Updates existing address lookup table (LUT) script which was missing few addresses that should exist on LUT.
> Fix: Matching Engine address LUT script

- solver/src/utils/placeInitialOffer.ts
After the V2 SDK migration, this bug was introduced
> solver: fix `derivePostedVaaKey` args

- solana/ts/src/matchingEngine/index.ts
- solana/ts/src/utils.ts
solana/ts: make ArrayQueue dequeue safer
> solana/ts: add parsed transaction to callback

- evm/package.json
- evm/ts/tests/00__environment.ts
- evm/ts/tests/01__registration.ts
- evm/ts/tests/02__configuration.ts
- evm/ts/tests/03__marketOrder.ts
- evm/ts/tests/04__fastMarketOrder.ts
- package-lock.json
- Make ethers-v5 explicit so integrators know which ethers is being used when looking at the source
Adding an issue to upgrade ethers V5 to V6 in case the npm install vulnerability warnings scare integrators too much.
> evm: npm i ethers-v5 --save-prod

- solana/programs/token-router/src/composite/mod.rs
- solana/programs/token-router/src/processor/redeem_fill/fast.rs
- solana/sh/run_test_validator.sh
Direct data mapping being enabled avoided this stack access violation from cropping up in the local validator test. In order to safely test any instruction's potential stack access violations, disable this feature: https://github.com/solana-labs/solana/blob/27eff8408b7223bb3c4ab70523f8a8dca3ca6645/sdk/src/feature_set.rs#L616. 
Fix for token router: moar boxing
> solana: fix redeem fast fill stack access violation

- evm/package.json
- package.json
- solana/package.json
- solver/package.json
- universal/ts/package.json
Update version number to match release.
> update version number
